apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-html
data:
  index.html: |
    <!doctype html>
    <html>
      <head>
        <meta charset="utf-8" />
        <title>PWC Workbench – Hello</title>
        <style>
          body { font-family: system-ui, Arial; margin: 40px; line-height: 1.5; }
          .card { max-width: 720px; padding: 24px; border: 1px solid #ddd; border-radius: 12px; }
          h1 { margin-top: 0; }
          code { background: #f6f8fa; padding: 2px 6px; border-radius: 6px; }
        </style>
      </head>
      <body>
        <div class="card">
          <h1>✅ Deployed from Workbench (Global CaaS)</h1>
          <p>This page is served by an NGINX container with a tiny Helm chart.</p>
          <p>We’ll replace this with your chatbot UI later.</p>
        </div>
      </body>
    </html>
